 var LangPublicJson = [
	{ "KeyName" :"Account_LoginViewModel_ForgetPassword" , "KeyType" : "ModalView_PropertyName", "zh_CN" : "忘记密码 ？","zh_HK" : "忘記密碼 ？","en_US" : "Forget Password ？","IndustryIdArr" : "","MainComIdArr" : "" },
	{ "KeyName" :"Account_LoginViewModel_Title" , "KeyType" : "Modalview_PropertyName", "zh_CN" : "用户登录","zh_HK" : "用戶登錄","en_US" : "Login","IndustryIdArr" : "0","MainComIdArr" : "" },
	{ "KeyName" :"AspNetUser_Email" , "KeyType" : "Modal_PropertyName", "zh_CN" : "Email","zh_HK" : "Email","en_US" : "Email","IndustryIdArr" : "","MainComIdArr" : "" },
	{ "KeyName" :"AspNetUser_Password" , "KeyType" : "GeneralUI_Name", "zh_CN" : "Password","zh_HK" : "Password","en_US" : "Password","IndustryIdArr" : "0","MainComIdArr" : "" },
	{ "KeyName" :"AspNetUsers_AccessFailedCount" , "KeyType" : "Modal_PropertyName", "zh_CN" : "尝试登录","zh_HK" : "嘗試登錄","en_US" : "Access Failed Count","IndustryIdArr" : "0","MainComIdArr" : "" },
	{ "KeyName" :"AspNetUsers_Email" , "KeyType" : "Modal_PropertyName", "zh_CN" : "Email","zh_HK" : "Email","en_US" : "Email","IndustryIdArr" : "0","MainComIdArr" : "" },
	{ "KeyName" :"AspNetUsers_EmailConfirmed" , "KeyType" : "Modal_PropertyName", "zh_CN" : "Email 确认","zh_HK" : "Email 确认","en_US" : "Email Confirmed","IndustryIdArr" : "0","MainComIdArr" : "" },
	{ "KeyName" :"AspNetUsers_IndustryId" , "KeyType" : "Modal_PropertyName", "zh_CN" : "IndustryId","zh_HK" : "IndustryId","en_US" : "","IndustryIdArr" : "","MainComIdArr" : "" },
	{ "KeyName" :"AspNetUsers_LockoutEnabled" , "KeyType" : "Modal_PropertyName", "zh_CN" : "登出锁定","zh_HK" : "登出鎖定","en_US" : "Lockout Enabled","IndustryIdArr" : "0","MainComIdArr" : "" },
	{ "KeyName" :"AspNetUsers_MainComId" , "KeyType" : "Modal_PropertyName", "zh_CN" : "MainComId","zh_HK" : "MainComId","en_US" : "","IndustryIdArr" : "0","MainComIdArr" : "" },
	{ "KeyName" :"AspNetUsers_PhoneNumber" , "KeyType" : "Modal_PropertyName", "zh_CN" : "手机号码","zh_HK" : "手機號碼","en_US" : "Phone","IndustryIdArr" : "0","MainComIdArr" : "" },
	{ "KeyName" :"AspNetUsers_PhoneNumberConfirmed" , "KeyType" : "Modal_PropertyName", "zh_CN" : "手机号码确认","zh_HK" : "手機號碼確認","en_US" : "Phone Number Confirmed","IndustryIdArr" : "0","MainComIdArr" : "" },
	{ "KeyName" :"AspNetUsers_UserID" , "KeyType" : "Modal_PropertyName", "zh_CN" : "系统用户ID","zh_HK" : "系統用戶ID","en_US" : "Sys UserID","IndustryIdArr" : "0","MainComIdArr" : "" },
	{ "KeyName" :"AspNetUsers_UserName" , "KeyType" : "Modal_PropertyName", "zh_CN" : "用户名称","zh_HK" : "用戶名稱","en_US" : "User Name","IndustryIdArr" : "0","MainComIdArr" : "" },
	{ "KeyName" :"AttendanceLog_AccesscardId" , "KeyType" : "Modal_PropertyName", "zh_CN" : "出入卡ID","zh_HK" : "出入卡ID","en_US" : "Accesscard Id","IndustryIdArr" : "","MainComIdArr" : "" },
	{ "KeyName" :"AttendanceLog_AttendanceLogId" , "KeyType" : "Modal_PropertyName", "zh_CN" : "识别记录ID","zh_HK" : "識別記錄ID","en_US" : "Log Id","IndustryIdArr" : "","MainComIdArr" : "" },
	{ "KeyName" :"AttendanceLog_CatchPictureFileName" , "KeyType" : "Modal_PropertyName", "zh_CN" : "记录画面","zh_HK" : "記錄畫面","en_US" : "Catch Pic","IndustryIdArr" : "","MainComIdArr" : "" },
	{ "KeyName" :"AttendanceLog_CnName" , "KeyType" : "Modal_PropertyName", "zh_CN" : "CnName","zh_HK" : "姓名","en_US" : "Name","IndustryIdArr" : "","MainComIdArr" : "" },
	{ "KeyName" :"AttendanceLog_CompanyName" , "KeyType" : "Modal_PropertyName", "zh_CN" : "公司","zh_HK" : "公司","en_US" : "Company","IndustryIdArr" : "","MainComIdArr" : "" },
	{ "KeyName" :"AttendanceLog_ContractorId" , "KeyType" : "Modal_PropertyName", "zh_CN" : "ContractorId","zh_HK" : "ContractorId","en_US" : "Contractor Id","IndustryIdArr" : "","MainComIdArr" : "" },
	{ "KeyName" :"AttendanceLog_ContractorName" , "KeyType" : "Modal_PropertyName", "zh_CN" : "合约商","zh_HK" : "合約商","en_US" : "Contractor","IndustryIdArr" : "","MainComIdArr" : "" },
	{ "KeyName" :"AttendanceLog_CratedDateTime" , "KeyType" : "Modal_PropertyName", "zh_CN" : "创建时间","zh_HK" : "創建時間","en_US" : "Crated Date","IndustryIdArr" : "","MainComIdArr" : "" },
	{ "KeyName" :"AttendanceLog_DepartmentId" , "KeyType" : "Modal_PropertyName", "zh_CN" : "Department Id","zh_HK" : "Department Id","en_US" : "Department Id","IndustryIdArr" : "","MainComIdArr" : "" },
	{ "KeyName" :"AttendanceLog_DepartmentName" , "KeyType" : "Modal_PropertyName", "zh_CN" : "部门","zh_HK" : "部門","en_US" : "Department","IndustryIdArr" : "","MainComIdArr" : "" },
	{ "KeyName" :"AttendanceLog_DeviceEntryMode" , "KeyType" : "Modal_PropertyName", "zh_CN" : "模式","zh_HK" : "模式","en_US" : "Entry Mode","IndustryIdArr" : "","MainComIdArr" : "" },
	{ "KeyName" :"AttendanceLog_DeviceName" , "KeyType" : "Modal_PropertyName", "zh_CN" : "设备","zh_HK" : "设备","en_US" : "Device","IndustryIdArr" : "","MainComIdArr" : "" },
	{ "KeyName" :"AttendanceLog_EmployeeId" , "KeyType" : "Modal_PropertyName", "zh_CN" : "雇员ID","zh_HK" : "雇員ID","en_US" : "EmployeeId","IndustryIdArr" : "","MainComIdArr" : "" },
	{ "KeyName" :"AttendanceLog_JobId" , "KeyType" : "Modal_PropertyName", "zh_CN" : "JobId","zh_HK" : "JobId","en_US" : "JobId","IndustryIdArr" : "","MainComIdArr" : "" },
	{ "KeyName" :"AttendanceLog_JobName" , "KeyType" : "Modal_PropertyName", "zh_CN" : "工种","zh_HK" : "工种","en_US" : "Job Name","IndustryIdArr" : "","MainComIdArr" : "" },
	{ "KeyName" :"AttendanceLog_MainComId" , "KeyType" : "Modal_PropertyName", "zh_CN" : "公司ID","zh_HK" : "公司ID","en_US" : "Com Id","IndustryIdArr" : "","MainComIdArr" : "" },
	{ "KeyName" :"AttendanceLog_OccurDateTime" , "KeyType" : "Modal_PropertyName", "zh_CN" : "记录时间","zh_HK" : "記錄時間","en_US" : "Occur Time","IndustryIdArr" : "","MainComIdArr" : "" },
	{ "KeyName" :"AttendanceLog_PositionId" , "KeyType" : "Modal_PropertyName", "zh_CN" : "职位","zh_HK" : "Position","en_US" : "Position","IndustryIdArr" : "","MainComIdArr" : "" },
	{ "KeyName" :"AttendanceLog_PositionTitle" , "KeyType" : "Modal_PropertyName", "zh_CN" : "职函","zh_HK" : "职函","en_US" : "Position Title","IndustryIdArr" : "","MainComIdArr" : "" },
	{ "KeyName" :"AttendanceLog_SiteId" , "KeyType" : "Modal_PropertyName", "zh_CN" : "SiteId","zh_HK" : "SiteId","en_US" : "Site Id","IndustryIdArr" : "","MainComIdArr" : "" },
	{ "KeyName" :"AttendanceLog_SiteName" , "KeyType" : "Modal_PropertyName", "zh_CN" : "位置名称","zh_HK" : "位置名稱","en_US" : "Site Name","IndustryIdArr" : "","MainComIdArr" : "" },
	{ "KeyName" :"AttendanceLog_Title" , "KeyType" : "ModalView_PropertyName", "zh_CN" : "识别记录","zh_HK" : "識別記錄","en_US" : "Recognization log","IndustryIdArr" : "","MainComIdArr" : "" },
	{ "KeyName" :"AttributeExtensions_CreditCardAttribute" , "KeyType" : "AttributeExtensions", "zh_CN" : "请输入正确的信用卡格式","zh_HK" : "請輸入正確的信用卡帳號格式","en_US" : "請輸入正確的信用卡帳號格式","IndustryIdArr" : "0","MainComIdArr" : "" },
	{ "KeyName" :"AttributeExtensions_CuitAttribute" , "KeyType" : "AttributeExtensions", "zh_CN" : "必須符合数字格式 如 12-12345678-1","zh_HK" : "必須符合数字格式 如 12-12345678-1","en_US" : "必須符合数字格式 如 12-12345678-1","IndustryIdArr" : "0","MainComIdArr" : "" },
	{ "KeyName" :"AttributeExtensions_DateAttribute" , "KeyType" : "AttributeExtensions", "zh_CN" : "请输入正确日期格式","zh_HK" : "請輸入正確的日期格式","en_US" : "請輸入正確的日期格式","IndustryIdArr" : "0","MainComIdArr" : "" },
	{ "KeyName" :"AttributeExtensions_DigitsAttribute" , "KeyType" : "AttributeExtensions", "zh_CN" : "请输入数字","zh_HK" : "請輸入數字","en_US" : "Only digital","IndustryIdArr" : "0","MainComIdArr" : "" },
	{ "KeyName" :"AttributeExtensions_EmailAttribute" , "KeyType" : "AttributeExtensions", "zh_CN" : "请输入正确的Email格式","zh_HK" : "請輸入正確的Email格式","en_US" : "Please enter the correct ema.il format","IndustryIdArr" : "0","MainComIdArr" : "" },
	{ "KeyName" :"AttributeExtensions_EqualToAttribute" , "KeyType" : "AttributeExtensions", "zh_CN" : "{0}不一致","zh_HK" : "{0}不一致","en_US" : "{0}不一致","IndustryIdArr" : "0","MainComIdArr" : "" },
	{ "KeyName" :"AttributeExtensions_FileExtensionsAttribute" , "KeyType" : "AttributeExtensions", "zh_CN" : "仅接受文件类型:.png,jpg,jpeg,gif","zh_HK" : "仅接受图片文件:.png,jpg,jpeg,gif","en_US" : "","IndustryIdArr" : "0","MainComIdArr" : "" },
	{ "KeyName" :"AttributeExtensions_MaxAttribute" , "KeyType" : "AttributeExtensions", "zh_CN" : "{0}必须小于或等于{1}","zh_HK" : "{0}必須小於或等於{1}","en_US" : "","IndustryIdArr" : "0","MainComIdArr" : "" },
	{ "KeyName" :"AttributeExtensions_MinAttribute" , "KeyType" : "AttributeExtensions", "zh_CN" : "{0}必须大于{1}","zh_HK" : "{0}必须大于{1}","en_US" : "","IndustryIdArr" : "0","MainComIdArr" : "" },
	{ "KeyName" :"AttributeExtensions_NumericAttribute" , "KeyType" : "AttributeExtensions", "zh_CN" : "请输入有效的数字","zh_HK" : "請輸入有效的數字","en_US" : "","IndustryIdArr" : "0","MainComIdArr" : "" },
	{ "KeyName" :"AttributeExtensions_PhoneNumber" , "KeyType" : "AttributeExtensions", "zh_CN" : "请输入正确的手机号码。","zh_HK" : "請輸入正確的手机号码。","en_US" : "Please enter the correct phone number.","IndustryIdArr" : "0","MainComIdArr" : "" },
	{ "KeyName" :"AttributeExtensions_PhoneNumberAttribute" , "KeyType" : "AttributeExtensions", "zh_CN" : "输入的手机号码不正确,格式如: 13812345678","zh_HK" : "輸入手機號碼格式如: 60123456","en_US" : "輸入手機號碼格式如: 60123456","IndustryIdArr" : "0","MainComIdArr" : "" },
	{ "KeyName" :"AttributeExtensions_UrlAttribute_Optional_Invalid" , "KeyType" : "AttributeExtensions", "zh_CN" : "请输入完整的url连接","zh_HK" : "請輸入完整的url","en_US" : "","IndustryIdArr" : "0","MainComIdArr" : "" },
	{ "KeyName" :"AttributeExtensions_UrlAttribute_Protocol_Invalid" , "KeyType" : "AttributeExtensions", "zh_CN" : "无效的URL","zh_HK" : "無效的url","en_US" : "","IndustryIdArr" : "0","MainComIdArr" : "" },
	{ "KeyName" :"AttributeExtensions_UrlAttribute_validHttp" , "KeyType" : "AttributeExtensions", "zh_CN" : "请输入有效的http,https,ftp等开头的链接","zh_HK" : "{0} 不是有效的http,https等開頭的連接","en_US" : "","IndustryIdArr" : "0","MainComIdArr" : "" },
	{ "KeyName" :"AttributeExtensions_YearAttribute" , "KeyType" : "AttributeExtensions", "zh_CN" : "请输入有效年份格式","zh_HK" : "請輸入有效的年份格式","en_US" : "","IndustryIdArr" : "0","MainComIdArr" : "" },
	{ "KeyName" :"AutoCalcMissingType_AutoMissingLunchEnd" , "KeyType" : "Modal_PropertyName", "zh_CN" : "自动计算漏打午餐结束时间","zh_HK" : "自動計算漏打午餐結束時間","en_US" : "AutoCalc of Lunch End Missings","IndustryIdArr" : "","MainComIdArr" : "" },
	{ "KeyName" :"AutoCalcMissingType_AutoMissingLunchStart" , "KeyType" : "Modal_PropertyName", "zh_CN" : "自动计算漏打午餐开始时间","zh_HK" : "自動計算漏打午餐開始時間","en_US" : "AutoCalc of Lunch Start Missings","IndustryIdArr" : "","MainComIdArr" : "" },
	{ "KeyName" :"AutoCalcMissingType_AutoMissingWorkOff" , "KeyType" : "Modal_PropertyName", "zh_CN" : "下班漏打自动计算","zh_HK" : "下班漏打自動計算","en_US" : "AutoCalc of Workoff  Missings","IndustryIdArr" : "","MainComIdArr" : "" },
	{ "KeyName" :"AutoCalcMissingType_AutoMissingWorkOn" , "KeyType" : "Modal_PropertyName", "zh_CN" : "上班漏打自动计算","zh_HK" : "上班漏打自動計算","en_US" : "AutoCalc of Workon  Missings","IndustryIdArr" : "","MainComIdArr" : "" },
	{ "KeyName" :"AutoCalcMissingType_ManualMissingLunchEnd" , "KeyType" : "Modal_PropertyName", "zh_CN" : "手动计算漏打午餐结束时间","zh_HK" : "手動計算漏打午餐結束時間","en_US" : "Manual Missing Lunch End","IndustryIdArr" : "","MainComIdArr" : "" },
	{ "KeyName" :"AutoCalcMissingType_ManualMissingLunchStart" , "KeyType" : "Modal_PropertyName", "zh_CN" : "手动计算漏打午餐开始时间","zh_HK" : "手動計算漏打午餐開始時間","en_US" : "Manual Missing LunchStart","IndustryIdArr" : "","MainComIdArr" : "" },
	{ "KeyName" :"AutoCalcMissingType_ManualWorkOffMissing" , "KeyType" : "Modal_PropertyName", "zh_CN" : "手动调整下班漏打","zh_HK" : "手動調整下班漏打","en_US" : "Manual WorkOn Missing","IndustryIdArr" : "","MainComIdArr" : "" },
	{ "KeyName" :"AutoCalcMissingType_ManualWorkOnMissing" , "KeyType" : "Modal_PropertyName", "zh_CN" : "手动调整上班漏打","zh_HK" : "手動調整上班漏打","en_US" : "Manual WorkOn Missing","IndustryIdArr" : "","MainComIdArr" : "" },
	{ "KeyName" :"AutoCalcMissingType_NoMissing" , "KeyType" : "Modal_PropertyName", "zh_CN" : "无漏打","zh_HK" : "無漏打","en_US" : "No Missing","IndustryIdArr" : "","MainComIdArr" : "" },
	{ "KeyName" :"CalcMissingMode_AUTO" , "KeyType" : "Modal_PropertyName", "zh_CN" : "自动","zh_HK" : "自动","en_US" : "AUTO","IndustryIdArr" : "","MainComIdArr" : "" },
	{ "KeyName" :"CalcMissingMode_MANUAL" , "KeyType" : "Modal_PropertyName", "zh_CN" : "手动","zh_HK" : "手动","en_US" : "MANUAL","IndustryIdArr" : "","MainComIdArr" : "" },
	{ "KeyName" :"CalcMissingMode_RESERVED_TO_DO" , "KeyType" : "Modal_PropertyName", "zh_CN" : "RTD","zh_HK" : "RTD","en_US" : "RTD","IndustryIdArr" : "","MainComIdArr" : "" },
	{ "KeyName" :"CalcPeriodType_DEFINITION" , "KeyType" : "Modal_PropertyName", "zh_CN" : "自定义","zh_HK" : "自定義","en_US" : "Definition","IndustryIdArr" : "","MainComIdArr" : "" },
	{ "KeyName" :"Contractor_CompanyAddress" , "KeyType" : "Modal_PropertyName", "zh_CN" : "公司地址","zh_HK" : "公司地址","en_US" : "","IndustryIdArr" : "0","MainComIdArr" : "" },
	{ "KeyName" :"Contractor_CompanyFax" , "KeyType" : "Modal_PropertyName", "zh_CN" : "公司传真","zh_HK" : "公司傳真","en_US" : "","IndustryIdArr" : "0","MainComIdArr" : "" },
	{ "KeyName" :"Contractor_CompanyName" , "KeyType" : "Modal_PropertyName", "zh_CN" : "第三方服务公司名称","zh_HK" : "第三方服務公司名稱","en_US" : "","IndustryIdArr" : "0","MainComIdArr" : "" },
	{ "KeyName" :"Contractor_CompanyNameLogo" , "KeyType" : "Modal_PropertyName", "zh_CN" : "公司Logo","zh_HK" : "公司Logo","en_US" : "","IndustryIdArr" : "0","MainComIdArr" : "" },
	{ "KeyName" :"Contractor_CompanyTel" , "KeyType" : "Modal_PropertyName", "zh_CN" : "公司电话","zh_HK" : "公司電話","en_US" : "","IndustryIdArr" : "0","MainComIdArr" : "" },
	{ "KeyName" :"Contractor_ContactName" , "KeyType" : "Modal_PropertyName", "zh_CN" : "公司联系人","zh_HK" : "公司聯系人","en_US" : "","IndustryIdArr" : "0","MainComIdArr" : "" },
	{ "KeyName" :"Contractor_ContactPhone" , "KeyType" : "Modal_PropertyName", "zh_CN" : "联系人手机","zh_HK" : "聯系人手機","en_US" : "","IndustryIdArr" : "0","MainComIdArr" : "" },
	{ "KeyName" :"Contractor_ContractorNo" , "KeyType" : "Modal_PropertyName", "zh_CN" : "合约编号","zh_HK" : "合約編號","en_US" : "","IndustryIdArr" : "0","MainComIdArr" : "" },
	{ "KeyName" :"Contractor_IndustryId" , "KeyType" : "Modal_PropertyName", "zh_CN" : "行业Id","zh_HK" : "行業Id","en_US" : "","IndustryIdArr" : "0","MainComIdArr" : "" },
	{ "KeyName" :"Contractor_IndustryName" , "KeyType" : "Modal_PropertyName", "zh_CN" : "所属行业","zh_HK" : "所屬行業","en_US" : "","IndustryIdArr" : "0","MainComIdArr" : "" },
	{ "KeyName" :"Contractor_MainComId" , "KeyType" : "Modal_PropertyName", "zh_CN" : "ContractorId","zh_HK" : "ContractorId","en_US" : "","IndustryIdArr" : "0","MainComIdArr" : "" },
	{ "KeyName" :"Contractor_OperatedDate" , "KeyType" : "Modal_PropertyName", "zh_CN" : "操作日期","zh_HK" : "操作日期","en_US" : "","IndustryIdArr" : "0","MainComIdArr" : "" },
	{ "KeyName" :"Contractor_OperatedUserName" , "KeyType" : "Modal_PropertyName", "zh_CN" : "操作用户","zh_HK" : "操作用戶","en_US" : "","IndustryIdArr" : "0","MainComIdArr" : "" },
	{ "KeyName" :"Contractor_ServiceEndDate" , "KeyType" : "Modal_PropertyName", "zh_CN" : "服务结束日期","zh_HK" : "服務結束日期","en_US" : "","IndustryIdArr" : "0","MainComIdArr" : "" },
	{ "KeyName" :"Contractor_ServiceStartDate" , "KeyType" : "Modal_PropertyName", "zh_CN" : "服务启动日期","zh_HK" : "服務啟動日期","en_US" : "","IndustryIdArr" : "0","MainComIdArr" : "" },
	{ "KeyName" :"Dashbord_Index_Title" , "KeyType" : "ModalView_PropertyName", "zh_CN" : "仪表板 Dashbord","zh_HK" : "仪表板 Dashbord","en_US" : "Dashbord","IndustryIdArr" : "0","MainComIdArr" : "" },
	{ "KeyName" :"Department_CompanyAbbreviation" , "KeyType" : "Modal_PropertyName", "zh_CN" : "部門名稱","zh_HK" : "部門名稱","en_US" : "部門名稱","IndustryIdArr" : "","MainComIdArr" : "" },
	{ "KeyName" :"Department_CompanyName" , "KeyType" : "Modal_PropertyName", "zh_CN" : "所屬公司","zh_HK" : "所屬公司","en_US" : "所屬公司","IndustryIdArr" : "","MainComIdArr" : "" },
	{ "KeyName" :"Department_DepartmentAbbrName" , "KeyType" : "Modal_PropertyName", "zh_CN" : "部門簡稱","zh_HK" : "部門簡稱","en_US" : "部門簡稱","IndustryIdArr" : "","MainComIdArr" : "" },
	{ "KeyName" :"Department_DepartmentId" , "KeyType" : "Modal_PropertyName", "zh_CN" : "DepartmentId","zh_HK" : "DepartmentId","en_US" : "DepartmentId","IndustryIdArr" : "","MainComIdArr" : "" },
	{ "KeyName" :"Department_MainComId" , "KeyType" : "Modal_PropertyName", "zh_CN" : "MainComId","zh_HK" : "MainComId","en_US" : "MainComId","IndustryIdArr" : "","MainComIdArr" : "" },
	{ "KeyName" :"DeviceEntryMode_IN" , "KeyType" : "Modal_PropertyName", "zh_CN" : "入口类型设备","zh_HK" : "入口類型設備","en_US" : "Entry Device","IndustryIdArr" : "","MainComIdArr" : "" },
	{ "KeyName" :"DeviceEntryMode_OUT" , "KeyType" : "Modal_PropertyName", "zh_CN" : "出口类型设备","zh_HK" : "出口類型設備","en_US" : "Exit Device","IndustryIdArr" : "","MainComIdArr" : "" },
	{ "KeyName" :"DeviceEntryMode_UNDEFINED" , "KeyType" : "Modal_PropertyName", "zh_CN" : "未定义","zh_HK" : "未定義","en_US" : "undefined","IndustryIdArr" : "","MainComIdArr" : "" },
	{ "KeyName" :"Employee_AccessCardId" , "KeyType" : "Modal_PropertyName", "zh_CN" : "通行卡ID","zh_HK" : "通行卡ID","en_US" : "AccessCardId","IndustryIdArr" : "0","MainComIdArr" : "" },
	{ "KeyName" :"Employee_Birthday" , "KeyType" : "Modal_PropertyName", "zh_CN" : "出生日期","zh_HK" : "出生日期","en_US" : "Birthday","IndustryIdArr" : "0","MainComIdArr" : "" },
	{ "KeyName" :"Employee_CnName" , "KeyType" : "Modal_PropertyName", "zh_CN" : "中文姓名","zh_HK" : "姓名","en_US" : "Chinese Name","IndustryIdArr" : "0","MainComIdArr" : "" },
	{ "KeyName" :"Employee_ContractorId" , "KeyType" : "Modal_PropertyName", "zh_CN" : "所属于第三方","zh_HK" : "所屬于第三方","en_US" : "ContractorId","IndustryIdArr" : "0","MainComIdArr" : "" },
	{ "KeyName" :"Employee_ContractorName" , "KeyType" : "Modal_PropertyName", "zh_CN" : "The 3Rd 服务公司名称","zh_HK" : "The 3Rd 服務公司名稱","en_US" : "The 3Rd 服务公司名称","IndustryIdArr" : "","MainComIdArr" : "" },
	{ "KeyName" :"Employee_CreatedDate" , "KeyType" : "Modal_PropertyName", "zh_CN" : "创建日期","zh_HK" : "創建日期","en_US" : "CreatedDate","IndustryIdArr" : "0","MainComIdArr" : "" },
	{ "KeyName" :"Employee_Department" , "KeyType" : "Modal_PropertyName", "zh_CN" : "部门","zh_HK" : "部門","en_US" : "Department","IndustryIdArr" : "","MainComIdArr" : "" },
	{ "KeyName" :"Employee_DepartmentId" , "KeyType" : "Modal_PropertyName", "zh_CN" : "部門ID","zh_HK" : "部門ID","en_US" : "部門ID","IndustryIdArr" : "","MainComIdArr" : "" },
	{ "KeyName" :"Employee_DepartmentName" , "KeyType" : "Modal_PropertyName", "zh_CN" : "部門名稱","zh_HK" : "部門名稱","en_US" : "部門名稱","IndustryIdArr" : "","MainComIdArr" : "" },
	{ "KeyName" :"Employee_Email" , "KeyType" : "Modal_PropertyName", "zh_CN" : "Email","zh_HK" : "Email","en_US" : "Email","IndustryIdArr" : "0","MainComIdArr" : "" },
	{ "KeyName" :"Employee_EmployeeId" , "KeyType" : "Modal_PropertyName", "zh_CN" : "ID","zh_HK" : "ID","en_US" : "ID","IndustryIdArr" : "0","MainComIdArr" : "" },
	{ "KeyName" :"Employee_EnrollmentDate" , "KeyType" : "Modal_PropertyName", "zh_CN" : "入职日期","zh_HK" : "入職日期","en_US" : "EnrollmentDate","IndustryIdArr" : "0","MainComIdArr" : "" },
	{ "KeyName" :"Employee_FirstName" , "KeyType" : "Modal_PropertyName", "zh_CN" : "姓","zh_HK" : "姓","en_US" : "FirstName","IndustryIdArr" : "0","MainComIdArr" : "" },
	{ "KeyName" :"Employee_Gender " , "KeyType" : "Modal_PropertyName", "zh_CN" : "性别","zh_HK" : "性別","en_US" : "Gender ","IndustryIdArr" : "0","MainComIdArr" : "" },
	{ "KeyName" :"Employee_IsBlock" , "KeyType" : "Modal_PropertyName", "zh_CN" : "黑名單（豁免考勤）","zh_HK" : "黑名單（豁免考勤）","en_US" : "Blocked（Attendance Exemption）","IndustryIdArr" : "0","MainComIdArr" : "" },
	{ "KeyName" :"Employee_Job" , "KeyType" : "Modal_PropertyName", "zh_CN" : "工 种","zh_HK" : "工 種","en_US" : "Job Type","IndustryIdArr" : "","MainComIdArr" : "" },
	{ "KeyName" :"Employee_JobId" , "KeyType" : "Modal_PropertyName", "zh_CN" : "工種編號","zh_HK" : "工種編號","en_US" : "工種編號","IndustryIdArr" : "","MainComIdArr" : "" },
	{ "KeyName" :"Employee_JobName" , "KeyType" : "Modal_PropertyName", "zh_CN" : "工種名稱","zh_HK" : "工種名稱","en_US" : "工種名稱","IndustryIdArr" : "","MainComIdArr" : "" },
	{ "KeyName" :"Employee_LastName" , "KeyType" : "Modal_PropertyName", "zh_CN" : "LastName","zh_HK" : "LastName","en_US" : "LastName","IndustryIdArr" : "0","MainComIdArr" : "" },
	{ "KeyName" :"Employee_LeaveDate" , "KeyType" : "Modal_PropertyName", "zh_CN" : "离职日期","zh_HK" : "離職日期","en_US" : "LeaveDate","IndustryIdArr" : "0","MainComIdArr" : "" },
	{ "KeyName" :"Employee_MainComId" , "KeyType" : "Modal_PropertyName", "zh_CN" : "公司ID","zh_HK" : "公司ID","en_US" : "MainComId","IndustryIdArr" : "0","MainComIdArr" : "" },
	{ "KeyName" :"Employee_OperatedDate" , "KeyType" : "Modal_PropertyName", "zh_CN" : "操作日期","zh_HK" : "操作日期","en_US" : "OperatedDate","IndustryIdArr" : "0","MainComIdArr" : "" },
	{ "KeyName" :"Employee_OperatedUserName" , "KeyType" : "Modal_PropertyName", "zh_CN" : "操作用户","zh_HK" : "操作用戶","en_US" : "OperatedUserName","IndustryIdArr" : "0","MainComIdArr" : "" },
	{ "KeyName" :"Employee_ParentUserId" , "KeyType" : "Modal_PropertyName", "zh_CN" : "ParentUserId","zh_HK" : "ParentUserId","en_US" : "ParentUserId","IndustryIdArr" : "0","MainComIdArr" : "" },
	{ "KeyName" :"Employee_PhoneNumber" , "KeyType" : "Modal_PropertyName", "zh_CN" : "手机","zh_HK" : "手機","en_US" : "手機","IndustryIdArr" : "0","MainComIdArr" : "" },
	{ "KeyName" :"Employee_Position" , "KeyType" : "Modal_PropertyName", "zh_CN" : "职 位","zh_HK" : "職 位","en_US" : "Position","IndustryIdArr" : "","MainComIdArr" : "" },
	{ "KeyName" :"Employee_PositionId" , "KeyType" : "Modal_PropertyName", "zh_CN" : "PositionId","zh_HK" : "PositionId","en_US" : "PositionId","IndustryIdArr" : "","MainComIdArr" : "" },
	{ "KeyName" :"Employee_PositionTitle" , "KeyType" : "Modal_PropertyName", "zh_CN" : "Position Title","zh_HK" : "Position Title","en_US" : "Position Title","IndustryIdArr" : "","MainComIdArr" : "" },
	{ "KeyName" :"Employee_Remarks" , "KeyType" : "Modal_PropertyName", "zh_CN" : "备注","zh_HK" : "備注","en_US" : "備注","IndustryIdArr" : "0","MainComIdArr" : "" },
	{ "KeyName" :"Employee_SiteId" , "KeyType" : "Modal_PropertyName", "zh_CN" : "SiteId","zh_HK" : "SiteId","en_US" : "SiteId","IndustryIdArr" : "","MainComIdArr" : "" },
	{ "KeyName" :"Employee_SiteName" , "KeyType" : "Modal_PropertyName", "zh_CN" : "地盤名稱","zh_HK" : "地盤名稱","en_US" : "Site Name","IndustryIdArr" : "","MainComIdArr" : "" },
	{ "KeyName" :"Employee_The3rdPartyEmployeeId" , "KeyType" : "Modal_PropertyName", "zh_CN" : "The 3rd Party EmployeeID","zh_HK" : "The 3rd Party EmployeeID","en_US" : "The 3rd Party EmployeeID","IndustryIdArr" : "0","MainComIdArr" : "" },
	{ "KeyName" :"Employee_UserIcon" , "KeyType" : "Modal_PropertyName", "zh_CN" : "UserIcon","zh_HK" : "UserIcon","en_US" : "UserIcon","IndustryIdArr" : "0","MainComIdArr" : "" },
	{ "KeyName" :"Employee_UserId" , "KeyType" : "Modal_PropertyName", "zh_CN" : "UserId","zh_HK" : "UserId","en_US" : "UserId","IndustryIdArr" : "0","MainComIdArr" : "" },
	{ "KeyName" :"EmployeeDetails_AccessCardId_Required" , "KeyType" : "ModalView_PropertyName", "zh_CN" : "请填入个人识别码。","zh_HK" : "請填入個人識別碼。","en_US" : "Please input personal Access Id.","IndustryIdArr" : "","MainComIdArr" : "" },
	{ "KeyName" :"EmployeeDetails_AddNewSuccess" , "KeyType" : "ModalView_PropertyName", "zh_CN" : "新增成功","zh_HK" : "新增成功","en_US" : "Add New Sucess !","IndustryIdArr" : "0","MainComIdArr" : "" },
	{ "KeyName" :"EmployeeDetails_BasicPersonalDetail" , "KeyType" : "ModalView_PropertyName", "zh_CN" : "基本资料","zh_HK" : "基本資料","en_US" : "Basic Personal Detail","IndustryIdArr" : "0","MainComIdArr" : "" },
	{ "KeyName" :"EmployeeDetails_CnNameTips" , "KeyType" : "ModalView_PropertyName", "zh_CN" : "如果没有中文名字，则请填入英文名字","zh_HK" : "如果沒有中文名字，則請填入英文名字","en_US" : "If there is no Chinese name, please fill in the English name","IndustryIdArr" : "","MainComIdArr" : "" },
	{ "KeyName" :"EmployeeDetails_DepartmentId_Required" , "KeyType" : "ModalView_PropertyName", "zh_CN" : "请选择那一个部门。","zh_HK" : "請選擇那一個部門。","en_US" : "Please select which department.","IndustryIdArr" : "","MainComIdArr" : "" },
	{ "KeyName" :"EmployeeDetails_FailAsHasExistsEmployRecord" , "KeyType" : "ModalView_PropertyName", "zh_CN" : "当前已经存在系统用户记录，请通过系统用户列表查询。","zh_HK" : "當前已經存在系統用戶記錄，請通過系統用戶列表查詢。","en_US" : "The system user record already exists. Please query through the system user list.","IndustryIdArr" : "0","MainComIdArr" : "" },
	{ "KeyName" :"EmployeeDetails_LeaveDateTips" , "KeyType" : "ModalView_PropertyName", "zh_CN" : "处于在职状态下，必须保持与入职登记日期（EnrollmentDate）一致。","zh_HK" : "處于在職狀態下，必須保持與入職登記日期（EnrollmentDate）一致。","en_US" : "In the active position, it must remain consistent with the Enrollment Date.","IndustryIdArr" : "","MainComIdArr" : "" },
	{ "KeyName" :"EmployeeDetails_TerminalDeviceIdSyncResultFail" , "KeyType" : "ModalView_PropertyName", "zh_CN" : "无法将新设备用户提交到终端。","zh_HK" : "無法將新設備用戶提交到終端。","en_US" : "Fail to Submit a new device User to terminal.","IndustryIdArr" : "","MainComIdArr" : "" },
	{ "KeyName" :"EmployeeDetails_TerminalDeviceIdSyncResultOK" , "KeyType" : "ModalView_PropertyName", "zh_CN" : "成功提交用户终端设备记录待执行。","zh_HK" : "成功提交用戶終端設備記錄待執行。","en_US" : "Submit a new device User to terminal in queue.","IndustryIdArr" : "","MainComIdArr" : "" },
	{ "KeyName" :"EmployeeDetails_Title" , "KeyType" : "ModalView_PropertyName", "zh_CN" : "雇员入职资料","zh_HK" : "雇員入職資料","en_US" : "Employee Detail","IndustryIdArr" : "0","MainComIdArr" : "" },
	{ "KeyName" :"EmployeeDetails_UpdateFailure" , "KeyType" : "ModalView_PropertyName", "zh_CN" : "更新失败","zh_HK" : "更新失敗","en_US" : "Update Fail ！","IndustryIdArr" : "0","MainComIdArr" : "" },
	{ "KeyName" :"EmployeeDetails_UpdateSuccess" , "KeyType" : "ModalView_PropertyName", "zh_CN" : "更新成功","zh_HK" : "更新成功","en_US" : "Update Sucess !","IndustryIdArr" : "0","MainComIdArr" : "" },
	{ "KeyName" :"EmployeeList_Title" , "KeyType" : "ModalView_PropertyName", "zh_CN" : "雇员列表","zh_HK" : "雇員列表","en_US" : "Employee List","IndustryIdArr" : "","MainComIdArr" : "" },
	{ "KeyName" :"GeneralUI_About" , "KeyType" : "GeneralUI_Name", "zh_CN" : "About Us","zh_HK" : "About Us","en_US" : "About Us","IndustryIdArr" : "0","MainComIdArr" : "" },
	{ "KeyName" :"GeneralUI_AddNew" , "KeyType" : "GeneralUI_Name", "zh_CN" : "新 增","zh_HK" : "新 增","en_US" : "Add New","IndustryIdArr" : "","MainComIdArr" : "" },
	{ "KeyName" :"GeneralUI_AttendanceSystem" , "KeyType" : "GeneralUI_Name", "zh_CN" : "考勤系统","zh_HK" : "考勤系統","en_US" : "Attendance System","IndustryIdArr" : "0","MainComIdArr" : "" },
	{ "KeyName" :"GeneralUI_Browse" , "KeyType" : "GeneralUI_Name", "zh_CN" : "浏 览","zh_HK" : "瀏 覽","en_US" : "Browse","IndustryIdArr" : "","MainComIdArr" : "" },
	{ "KeyName" :"GeneralUI_Cancel" , "KeyType" : "GeneralUI_Name", "zh_CN" : "取 消","zh_HK" : "取 消","en_US" : "Cancel","IndustryIdArr" : "0","MainComIdArr" : "" },
	{ "KeyName" :"GeneralUI_CnName" , "KeyType" : "GeneralUI_Name", "zh_CN" : "中文姓名","zh_HK" : "中文姓名","en_US" : "Chinese Name","IndustryIdArr" : "","MainComIdArr" : "" },
	{ "KeyName" :"GeneralUI_ComfirmedPassword" , "KeyType" : "GeneralUI_Name", "zh_CN" : "ComfirmedPassword","zh_HK" : "ComfirmedPassword","en_US" : "ComfirmedPassword","IndustryIdArr" : "0","MainComIdArr" : "" },
	{ "KeyName" :"GeneralUI_ConfirmPassword" , "KeyType" : "GeneralUI_Name", "zh_CN" : "Confirmed Password","zh_HK" : "Confirmed Password","en_US" : "Confirmed Password","IndustryIdArr" : "0","MainComIdArr" : "" },
	{ "KeyName" :"GeneralUI_Contact" , "KeyType" : "GeneralUI_Name", "zh_CN" : "联 系","zh_HK" : "聯 系","en_US" : "Contact Us","IndustryIdArr" : "0","MainComIdArr" : "" },
	{ "KeyName" :"GeneralUI_Create" , "KeyType" : "GeneralUI_Name", "zh_CN" : "创 建","zh_HK" : "創 建","en_US" : "Create","IndustryIdArr" : "0","MainComIdArr" : "" },
	{ "KeyName" :"GeneralUI_DataSending" , "KeyType" : "GeneralUI_Name", "zh_CN" : "数据发送中......","zh_HK" : "數據發送中......","en_US" : "Data Sending......","IndustryIdArr" : "0","MainComIdArr" : "" },
	{ "KeyName" :"GeneralUI_Date" , "KeyType" : "GeneralUI_Name", "zh_CN" : "请输入有效的日期格式","zh_HK" : "請輸入有效的日期格式","en_US" : "Please input valid date","IndustryIdArr" : "","MainComIdArr" : "" },
	{ "KeyName" :"GeneralUI_DateFormate" , "KeyType" : "GeneralUI_Name", "zh_CN" : "yyyy-MM-dd","zh_HK" : "yyyy-MM-dd","en_US" : "yyyy-MM-dd","IndustryIdArr" : "","MainComIdArr" : "" },
	{ "KeyName" :"GeneralUI_DateTimeFormate" , "KeyType" : "GeneralUI_Name", "zh_CN" : "yyyy/MM/dd","zh_HK" : "dd/MM/yyyy","en_US" : "yyyy/MM/dd","IndustryIdArr" : "","MainComIdArr" : "" },
	{ "KeyName" :"GeneralUI_DAYLY" , "KeyType" : "GeneralUI_Name", "zh_CN" : "每日","zh_HK" : "每日","en_US" : "DAYLY","IndustryIdArr" : "","MainComIdArr" : "" },
	{ "KeyName" :"GeneralUI_Delete" , "KeyType" : "GeneralUI_Name", "zh_CN" : "删 除","zh_HK" : "刪 除","en_US" : "Delete","IndustryIdArr" : "0","MainComIdArr" : "" },
	{ "KeyName" :"GeneralUI_Details" , "KeyType" : "GeneralUI_Name", "zh_CN" : "详 情","zh_HK" : "詳 情","en_US" : "Details","IndustryIdArr" : "0","MainComIdArr" : "" },
	{ "KeyName" :"GeneralUI_Email" , "KeyType" : "GeneralUI_Name", "zh_CN" : "Email","zh_HK" : "Email","en_US" : "Email","IndustryIdArr" : "0","MainComIdArr" : "" },
	{ "KeyName" :"GeneralUI_EnName" , "KeyType" : "GeneralUI_Name", "zh_CN" : "英文名","zh_HK" : "英文名","en_US" : "Eng Name","IndustryIdArr" : "","MainComIdArr" : "" },
	{ "KeyName" :"GeneralUI_Fail" , "KeyType" : "GeneralUI_Name", "zh_CN" : "失败 !","zh_HK" : "失敗 !","en_US" : "Fail ！","IndustryIdArr" : "0","MainComIdArr" : "" },
	{ "KeyName" :"GeneralUI_HomePage" , "KeyType" : "GeneralUI_Name", "zh_CN" : "主 页","zh_HK" : "主 頁","en_US" : "Home Page","IndustryIdArr" : "0","MainComIdArr" : "" },
	{ "KeyName" :"GeneralUI_Isee" , "KeyType" : "GeneralUI_Name", "zh_CN" : "I see","zh_HK" : "I see","en_US" : "I see","IndustryIdArr" : "0","MainComIdArr" : "" },
	{ "KeyName" :"GeneralUI_Login" , "KeyType" : "GeneralUI_Name", "zh_CN" : "登陸","zh_HK" : "Login","en_US" : "Login","IndustryIdArr" : "","MainComIdArr" : "" },
	{ "KeyName" :"GeneralUI_Logout" , "KeyType" : "GeneralUI_Name", "zh_CN" : "登出","zh_HK" : "登出","en_US" : "Logout","IndustryIdArr" : "","MainComIdArr" : "" },
	{ "KeyName" :"GeneralUI_MONTHLY" , "KeyType" : "GeneralUI_Name", "zh_CN" : "每月","zh_HK" : "每月","en_US" : "MONTHLY","IndustryIdArr" : "","MainComIdArr" : "" },
	{ "KeyName" :"GeneralUI_NO" , "KeyType" : "GeneralUI_Name", "zh_CN" : "No","zh_HK" : "No","en_US" : "No","IndustryIdArr" : "0","MainComIdArr" : "" },
	{ "KeyName" :"GeneralUI_OrderByDatetime" , "KeyType" : "GeneralUI_Name", "zh_CN" : "按时间排序","zh_HK" : "按時間排序","en_US" : "Order By Datetime","IndustryIdArr" : "","MainComIdArr" : "" },
	{ "KeyName" :"GeneralUI_Password" , "KeyType" : "GeneralUI_Name", "zh_CN" : "Password","zh_HK" : "Password","en_US" : "Password","IndustryIdArr" : "0","MainComIdArr" : "" },
	{ "KeyName" :"GeneralUI_PhoneNumber" , "KeyType" : "GeneralUI_Name", "zh_CN" : "PhoneNumber","zh_HK" : "PhoneNumber","en_US" : "PhoneNumber","IndustryIdArr" : "0","MainComIdArr" : "" },
	{ "KeyName" :"GeneralUI_PleaseSelectLanguage" , "KeyType" : "GeneralUI_Name", "zh_CN" : "请选择语言","zh_HK" : "請選擇語言","en_US" : "Please Select Language","IndustryIdArr" : "0","MainComIdArr" : "" },
	{ "KeyName" :"GeneralUI_Register" , "KeyType" : "GeneralUI_Name", "zh_CN" : "Register","zh_HK" : "Register","en_US" : "Register","IndustryIdArr" : "0","MainComIdArr" : "" },
	{ "KeyName" :"GeneralUI_Return" , "KeyType" : "GeneralUI_Name", "zh_CN" : "返 回","zh_HK" : "返 回","en_US" : "Return","IndustryIdArr" : "0","MainComIdArr" : "" },
	{ "KeyName" :"GeneralUI_ReturnResult" , "KeyType" : "GeneralUI_Name", "zh_CN" : "返回操作结果","zh_HK" : "返回操作結果","en_US" : "Return Operation Result","IndustryIdArr" : "0","MainComIdArr" : "" },
	{ "KeyName" :"GeneralUI_ReturnToList" , "KeyType" : "GeneralUI_Name", "zh_CN" : "返回列表","zh_HK" : "返回列表","en_US" : "Return to list","IndustryIdArr" : "0","MainComIdArr" : "" },
	{ "KeyName" :"GeneralUI_Select" , "KeyType" : "GeneralUI_Name", "zh_CN" : "选 择","zh_HK" : "選 擇","en_US" : "Select","IndustryIdArr" : "","MainComIdArr" : "" },
	{ "KeyName" :"GeneralUI_ServerError" , "KeyType" : "GeneralUI_Name", "zh_CN" : "发生服务器内容错误！","zh_HK" : "發生服務器內容錯誤！","en_US" : "Occur server internal error","IndustryIdArr" : "0","MainComIdArr" : "" },
	{ "KeyName" :"GeneralUI_Submit" , "KeyType" : "GeneralUI_Name", "zh_CN" : "Submit","zh_HK" : "Submit","en_US" : "Submit","IndustryIdArr" : "0","MainComIdArr" : "" },
	{ "KeyName" :"GeneralUI_Success" , "KeyType" : "GeneralUI_Name", "zh_CN" : "成 功","zh_HK" : "成 功","en_US" : "Success","IndustryIdArr" : "","MainComIdArr" : "" },
	{ "KeyName" :"GeneralUI_SysemLanguage" , "KeyType" : "GeneralUI_Name", "zh_CN" : "系统语言","zh_HK" : "系統語言","en_US" : "Sysem Language","IndustryIdArr" : "0","MainComIdArr" : "" },
	{ "KeyName" :"GeneralUI_System" , "KeyType" : "ModalView_PropertyName", "zh_CN" : "系 统","zh_HK" : "系 統","en_US" : "System","IndustryIdArr" : "0","MainComIdArr" : "" },
	{ "KeyName" :"GeneralUI_Update" , "KeyType" : "GeneralUI_Name", "zh_CN" : "更 新","zh_HK" : "更 新","en_US" : "Update","IndustryIdArr" : "0","MainComIdArr" : "" },
	{ "KeyName" :"GeneralUI_UserName" , "KeyType" : "GeneralUI_Name", "zh_CN" : "UserName","zh_HK" : "UserName","en_US" : "UserName","IndustryIdArr" : "0","MainComIdArr" : "" },
	{ "KeyName" :"GeneralUI_WEEKLY" , "KeyType" : "GeneralUI_Name", "zh_CN" : "每周","zh_HK" : "每周","en_US" : "WEEKLY","IndustryIdArr" : "","MainComIdArr" : "" },
	{ "KeyName" :"GeneralUI_YEARLY" , "KeyType" : "GeneralUI_Name", "zh_CN" : "每年","zh_HK" : "每年","en_US" : "YEARLY","IndustryIdArr" : "","MainComIdArr" : "" },
	{ "KeyName" :"GeneralUI_Yes" , "KeyType" : "GeneralUI_Name", "zh_CN" : "Yes","zh_HK" : "Yes","en_US" : "Yes","IndustryIdArr" : "0","MainComIdArr" : "" },
	{ "KeyName" :"HolidayPaidType_PAID_HOLIDAY" , "KeyType" : "Modal_PropertyName", "zh_CN" : "有薪公共假期","zh_HK" : "有薪公共假期","en_US" : "Paid holiday","IndustryIdArr" : "","MainComIdArr" : "" },
	{ "KeyName" :"HolidayPaidType_UNPAID_HOLIDAY" , "KeyType" : "Modal_PropertyName", "zh_CN" : "无薪公共假期","zh_HK" : "無薪公共假期","en_US" : "UNPAI HOLIDAY","IndustryIdArr" : "","MainComIdArr" : "" },
	{ "KeyName" :"Industry_EnIndustryName" , "KeyType" : "Modal_PropertyName", "zh_CN" : "Industry Name","zh_HK" : "Industry Name","en_US" : "","IndustryIdArr" : "0","MainComIdArr" : "" },
	{ "KeyName" :"Industry_IndustryId" , "KeyType" : "Modal_PropertyName", "zh_CN" : "Industry Id","zh_HK" : "Industry Id","en_US" : "","IndustryIdArr" : "0","MainComIdArr" : "" },
	{ "KeyName" :"Industry_IndustryName" , "KeyType" : "Modal_PropertyName", "zh_CN" : "Industry Name","zh_HK" : "Industry Name","en_US" : "","IndustryIdArr" : "0","MainComIdArr" : "" },
	{ "KeyName" :"Industry_ParentsIndustryId" , "KeyType" : "Modal_PropertyName", "zh_CN" : "Parents Id","zh_HK" : "Parents Id","en_US" : "","IndustryIdArr" : "0","MainComIdArr" : "" },
	{ "KeyName" :"Job_EnJobName" , "KeyType" : "Modal_PropertyName", "zh_CN" : "Job Eng Name","zh_HK" : "Job Eng Name","en_US" : "","IndustryIdArr" : "0","MainComIdArr" : "" },
	{ "KeyName" :"Job_IndustryId" , "KeyType" : "Modal_PropertyName", "zh_CN" : "Industry Id","zh_HK" : "Industry Id","en_US" : "","IndustryIdArr" : "0","MainComIdArr" : "" },
	{ "KeyName" :"Job_IndustryName" , "KeyType" : "Modal_PropertyName", "zh_CN" : "Industry Name","zh_HK" : "Industry Name","en_US" : "","IndustryIdArr" : "0","MainComIdArr" : "" },
	{ "KeyName" :"Job_JobId" , "KeyType" : "Modal_PropertyName", "zh_CN" : "Job Id","zh_HK" : "Job Id","en_US" : "","IndustryIdArr" : "0","MainComIdArr" : "" },
	{ "KeyName" :"Job_JobName" , "KeyType" : "Modal_PropertyName", "zh_CN" : "Job Name","zh_HK" : "Job Name","en_US" : "","IndustryIdArr" : "0","MainComIdArr" : "" },
	{ "KeyName" :"Job_The3rdJobId" , "KeyType" : "Modal_PropertyName", "zh_CN" : "The 3rd JobId","zh_HK" : "The 3rd JobId","en_US" : "","IndustryIdArr" : "0","MainComIdArr" : "" },
	{ "KeyName" :"Language_English" , "KeyType" : "Modal_PropertyName", "zh_CN" : "English","zh_HK" : "English","en_US" : "","IndustryIdArr" : "0","MainComIdArr" : "" },
	{ "KeyName" :"Language_IndustryId" , "KeyType" : "Modal_PropertyName", "zh_CN" : "Industry Id","zh_HK" : "Industry Id","en_US" : "","IndustryIdArr" : "0","MainComIdArr" : "" },
	{ "KeyName" :"Language_IsAppliedIndustry" , "KeyType" : "Modal_PropertyName", "zh_CN" : "應用行業術語","zh_HK" : "應用行業術語","en_US" : "應用行業術語","IndustryIdArr" : "","MainComIdArr" : "" },
	{ "KeyName" :"Language_KeyType" , "KeyType" : "Modal_PropertyName", "zh_CN" : "Key Type","zh_HK" : "Key Type","en_US" : "","IndustryIdArr" : "0","MainComIdArr" : "" },
	{ "KeyName" :"Language_Remark" , "KeyType" : "Modal_PropertyName", "zh_CN" : "Remark","zh_HK" : "Remark","en_US" : "","IndustryIdArr" : "0","MainComIdArr" : "" },
	{ "KeyName" :"Language_Simplify" , "KeyType" : "Modal_PropertyName", "zh_CN" : "Simplify","zh_HK" : "Simplify","en_US" : "","IndustryIdArr" : "0","MainComIdArr" : "" },
	{ "KeyName" :"Language_Traditional" , "KeyType" : "Modal_PropertyName", "zh_CN" : "Traditional","zh_HK" : "Traditional","en_US" : "","IndustryIdArr" : "0","MainComIdArr" : "" },
	{ "KeyName" :"LeavePaidType_PAID_LEAVE" , "KeyType" : "Modal_PropertyName", "zh_CN" : "有薪假期","zh_HK" : "有薪假期","en_US" : "Paid Leave","IndustryIdArr" : "","MainComIdArr" : "" },
	{ "KeyName" :"LeavePaidType_UNPAID_LEAVE" , "KeyType" : "Modal_PropertyName", "zh_CN" : "无薪假期","zh_HK" : "無薪假期","en_US" : "unpaid Leave","IndustryIdArr" : "","MainComIdArr" : "" },
	{ "KeyName" :"LeaveType_ANNUAL_LEAVE" , "KeyType" : "Modal_PropertyName", "zh_CN" : "年假","zh_HK" : "年假","en_US" : "ANNUAL_LEAVE","IndustryIdArr" : "","MainComIdArr" : "" },
	{ "KeyName" :"LeaveType_GENERAL_LEAVE" , "KeyType" : "Modal_PropertyName", "zh_CN" : "一般假期","zh_HK" : "一般假期","en_US" : "GENERAL LEAVE","IndustryIdArr" : "","MainComIdArr" : "" },
	{ "KeyName" :"LeaveType_SICK_LEAVE" , "KeyType" : "Modal_PropertyName", "zh_CN" : "病假","zh_HK" : "病假","en_US" : "SICK LEAVE","IndustryIdArr" : "","MainComIdArr" : "" },
	{ "KeyName" :"LeaveType_STATUTORY_HOLIDAY" , "KeyType" : "Modal_PropertyName", "zh_CN" : "公众假期","zh_HK" : "公眾假期","en_US" : "STATUTORY HOLIDAY","IndustryIdArr" : "","MainComIdArr" : "" },
	{ "KeyName" :"LeftMenu_EmployeeDetails_The3Rd_MenuTitle" , "KeyType" : "ModalView_PropertyName", "zh_CN" : "第三方服务2","zh_HK" : "第三方服務2","en_US" : "The 3rd Party Service 3","IndustryIdArr" : "0","MainComIdArr" : "" },
	{ "KeyName" :"LeftMenu_EmployeeFileCreate" , "KeyType" : "ModalView_PropertyName", "zh_CN" : "雇员资料创建","zh_HK" : "雇員資料創建","en_US" : "Employee File Create","IndustryIdArr" : "0","MainComIdArr" : "" },
	{ "KeyName" :"LeftMenu_EmployeeList_The3Rd_MenuTitle" , "KeyType" : "ModalView_PropertyName", "zh_CN" : "第三方服务1","zh_HK" : "第三方服務1","en_US" : "The 3rd Party Service 1","IndustryIdArr" : "0","MainComIdArr" : "" },
	{ "KeyName" :"LeftMenu_EmployeeManage" , "KeyType" : "ModalView_PropertyName", "zh_CN" : "雇员资料管理","zh_HK" : "雇員資料管理","en_US" : "Employee Manage","IndustryIdArr" : "0","MainComIdArr" : "" },
	{ "KeyName" :"LeftMenu_EmployeeSearchList" , "KeyType" : "ModalView_PropertyName", "zh_CN" : "考勤员工列表","zh_HK" : "考勤員工列表","en_US" : "Employee List","IndustryIdArr" : "","MainComIdArr" : "" },
	{ "KeyName" :"LeftMenu_ShiftSetting" , "KeyType" : "ModalView_PropertyName", "zh_CN" : "排班表设置","zh_HK" : "排班表設置","en_US" : "Shift Setting","IndustryIdArr" : "","MainComIdArr" : "" },
	{ "KeyName" :"LeftMenu_SystemManage" , "KeyType" : "ModalView_PropertyName", "zh_CN" : "系统管理","zh_HK" : "系統管理","en_US" : "System Manage","IndustryIdArr" : "0","MainComIdArr" : "" },
	{ "KeyName" :"LeftMenu_SystemSeeting" , "KeyType" : "ModalView_PropertyName", "zh_CN" : "系统业务设置","zh_HK" : "系統業務設置","en_US" : "Sys Bussiness Seeting","IndustryIdArr" : "","MainComIdArr" : "" },
	{ "KeyName" :"LeftMenu_SystemUser" , "KeyType" : "ModalView_PropertyName", "zh_CN" : "系统用户","zh_HK" : "系統用戶","en_US" : "System User","IndustryIdArr" : "0","MainComIdArr" : "" },
	{ "KeyName" :"LeftMenu_The3rdService" , "KeyType" : "ModalView_PropertyName", "zh_CN" : "第三方服务","zh_HK" : "第三方服務","en_US" : "The 3rd Party Service","IndustryIdArr" : "0","MainComIdArr" : "" },
	{ "KeyName" :"LoginPartialView_BackEnd" , "KeyType" : "GeneralUI_Name", "zh_CN" : "登陆返回","zh_HK" : "登陸返回","en_US" : "Back End","IndustryIdArr" : "0","MainComIdArr" : "" },
	{ "KeyName" :"MainCom_CIC_ReferenceNo" , "KeyType" : "Modal_PropertyName", "zh_CN" : "CIC Reference No.","zh_HK" : "CIC Reference No.","en_US" : "","IndustryIdArr" : "0","MainComIdArr" : "" },
	{ "KeyName" :"MainCom_CompanyAbbreviation" , "KeyType" : "Modal_PropertyName", "zh_CN" : "公司简称","zh_HK" : "公司簡稱","en_US" : "","IndustryIdArr" : "0","MainComIdArr" : "" },
	{ "KeyName" :"MainCom_CompanyAddress" , "KeyType" : "Modal_PropertyName", "zh_CN" : "公司地址","zh_HK" : "公司地址","en_US" : "","IndustryIdArr" : "0","MainComIdArr" : "" },
	{ "KeyName" :"MainCom_CompanyFax" , "KeyType" : "Modal_PropertyName", "zh_CN" : "公司传真","zh_HK" : "公司傳真","en_US" : "","IndustryIdArr" : "0","MainComIdArr" : "" },
	{ "KeyName" :"MainCom_CompanyLogo" , "KeyType" : "Modal_PropertyName", "zh_CN" : "公司Logo","zh_HK" : "公司Logo","en_US" : "","IndustryIdArr" : "0","MainComIdArr" : "" },
	{ "KeyName" :"MainCom_CompanyName" , "KeyType" : "Modal_PropertyName", "zh_CN" : "公司名称","zh_HK" : "公司名稱","en_US" : "","IndustryIdArr" : "0","MainComIdArr" : "" },
	{ "KeyName" :"MainCom_CompanyNameLogo" , "KeyType" : "Modal_PropertyName", "zh_CN" : "公司Logo","zh_HK" : "公司Logo","en_US" : "","IndustryIdArr" : "","MainComIdArr" : "" },
	{ "KeyName" :"MainCom_CompanyTel" , "KeyType" : "Modal_PropertyName", "zh_CN" : "公司电话","zh_HK" : "公司電話","en_US" : "","IndustryIdArr" : "0","MainComIdArr" : "" },
	{ "KeyName" :"MainCom_ContactName" , "KeyType" : "Modal_PropertyName", "zh_CN" : "公司联系人","zh_HK" : "公司聯系人","en_US" : "","IndustryIdArr" : "0","MainComIdArr" : "" },
	{ "KeyName" :"MainCom_ContactPhone" , "KeyType" : "Modal_PropertyName", "zh_CN" : "联系人手机","zh_HK" : "聯系人手機","en_US" : "","IndustryIdArr" : "0","MainComIdArr" : "" },
	{ "KeyName" :"MainCom_ContractorNo" , "KeyType" : "Modal_PropertyName", "zh_CN" : "合约编号","zh_HK" : "合約編號","en_US" : "","IndustryIdArr" : "0","MainComIdArr" : "" },
	{ "KeyName" :"MainCom_IndustryId" , "KeyType" : "Modal_PropertyName", "zh_CN" : "行业Id","zh_HK" : "行業Id","en_US" : "","IndustryIdArr" : "0","MainComIdArr" : "" },
	{ "KeyName" :"MainCom_IndustryName" , "KeyType" : "Modal_PropertyName", "zh_CN" : "所属行业","zh_HK" : "所屬行業","en_US" : "","IndustryIdArr" : "0","MainComIdArr" : "" },
	{ "KeyName" :"MainCom_Latitude" , "KeyType" : "Modal_PropertyName", "zh_CN" : "纬度","zh_HK" : "緯度","en_US" : "","IndustryIdArr" : "0","MainComIdArr" : "" },
	{ "KeyName" :"MainCom_Longitude" , "KeyType" : "Modal_PropertyName", "zh_CN" : "经度","zh_HK" : "經度","en_US" : "","IndustryIdArr" : "0","MainComIdArr" : "" },
	{ "KeyName" :"MainCom_MainComId" , "KeyType" : "Modal_PropertyName", "zh_CN" : "MainComId","zh_HK" : "MainComId","en_US" : "","IndustryIdArr" : "0","MainComIdArr" : "" },
	{ "KeyName" :"MainCom_OperatedDate" , "KeyType" : "Modal_PropertyName", "zh_CN" : "操作日期","zh_HK" : "操作日期","en_US" : "","IndustryIdArr" : "0","MainComIdArr" : "" },
	{ "KeyName" :"MainCom_OperatedUserName" , "KeyType" : "Modal_PropertyName", "zh_CN" : "操作用户","zh_HK" : "操作用戶","en_US" : "","IndustryIdArr" : "0","MainComIdArr" : "" },
	{ "KeyName" :"MainCom_ServiceEndDate" , "KeyType" : "Modal_PropertyName", "zh_CN" : "服務結束日期","zh_HK" : "服務結束日期","en_US" : "","IndustryIdArr" : "0","MainComIdArr" : "" },
	{ "KeyName" :"MainCom_ServiceStartDate" , "KeyType" : "Modal_PropertyName", "zh_CN" : "服務開始日期","zh_HK" : "服務開始日期","en_US" : "","IndustryIdArr" : "0","MainComIdArr" : "" },
	{ "KeyName" :"MainCom_ServiceStatus" , "KeyType" : "Modal_PropertyName", "zh_CN" : "服務狀態","zh_HK" : "服務狀態","en_US" : "","IndustryIdArr" : "0","MainComIdArr" : "" },
	{ "KeyName" :"MenuItem_EngMenuItemName" , "KeyType" : "Modal_PropertyName", "zh_CN" : "菜单名称","zh_HK" : "菜單名稱","en_US" : "","IndustryIdArr" : "0","MainComIdArr" : "" },
	{ "KeyName" :"MenuItem_ForRoleName" , "KeyType" : "Modal_PropertyName", "zh_CN" : "角色授权","zh_HK" : "角色授權","en_US" : "","IndustryIdArr" : "0","MainComIdArr" : "" },
	{ "KeyName" :"MenuItem_MenuItemID" , "KeyType" : "Modal_PropertyName", "zh_CN" : "菜单ID","zh_HK" : "菜單ID","en_US" : "","IndustryIdArr" : "0","MainComIdArr" : "" },
	{ "KeyName" :"MenuItem_MenuItemName" , "KeyType" : "Modal_PropertyName", "zh_CN" : "菜单名称","zh_HK" : "菜單名稱","en_US" : "","IndustryIdArr" : "0","MainComIdArr" : "" },
	{ "KeyName" :"MenuItem_MenuLink" , "KeyType" : "Modal_PropertyName", "zh_CN" : "连接","zh_HK" : "連接","en_US" : "","IndustryIdArr" : "0","MainComIdArr" : "" },
	{ "KeyName" :"MenuItem_OperatedDate" , "KeyType" : "Modal_PropertyName", "zh_CN" : "操作日期","zh_HK" : "操作日期","en_US" : "","IndustryIdArr" : "0","MainComIdArr" : "" },
	{ "KeyName" :"MenuItem_OperatedUserName" , "KeyType" : "Modal_PropertyName", "zh_CN" : "操作用户","zh_HK" : "操作用戶","en_US" : "","IndustryIdArr" : "0","MainComIdArr" : "" },
	{ "KeyName" :"MenuItem_ParentsMenuItemID" , "KeyType" : "Modal_PropertyName", "zh_CN" : "父菜单ID","zh_HK" : "父菜單ID","en_US" : "","IndustryIdArr" : "0","MainComIdArr" : "" },
	{ "KeyName" :"MenuItem_Target" , "KeyType" : "Modal_PropertyName", "zh_CN" : "打开方式","zh_HK" : "打開方式","en_US" : "","IndustryIdArr" : "0","MainComIdArr" : "" },
	{ "KeyName" :"Position_CreatedDate" , "KeyType" : "Modal_PropertyName", "zh_CN" : "CreatedDate","zh_HK" : "CreatedDate","en_US" : "","IndustryIdArr" : "0","MainComIdArr" : "" },
	{ "KeyName" :"Position_CreatedDate2" , "KeyType" : "Modal_PropertyName", "zh_CN" : "CreatedDate2","zh_HK" : "CreatedDate2","en_US" : "","IndustryIdArr" : "0","MainComIdArr" : "" },
	{ "KeyName" :"Position_EnPositionTitle" , "KeyType" : "Modal_PropertyName", "zh_CN" : "Position Eng Title","zh_HK" : "Position Eng Title","en_US" : "","IndustryIdArr" : "0","MainComIdArr" : "" },
	{ "KeyName" :"Position_IndustryId" , "KeyType" : "Modal_PropertyName", "zh_CN" : "Industry Id","zh_HK" : "Industry Id","en_US" : "","IndustryIdArr" : "0","MainComIdArr" : "" },
	{ "KeyName" :"Position_IndustryName" , "KeyType" : "Modal_PropertyName", "zh_CN" : "Industry Name","zh_HK" : "Industry Name","en_US" : "","IndustryIdArr" : "0","MainComIdArr" : "" },
	{ "KeyName" :"Position_PositionId" , "KeyType" : "Modal_PropertyName", "zh_CN" : "Position Id","zh_HK" : "Position Id","en_US" : "","IndustryIdArr" : "0","MainComIdArr" : "" },
	{ "KeyName" :"Position_PositionTitle" , "KeyType" : "Modal_PropertyName", "zh_CN" : "Position Title","zh_HK" : "Position Title","en_US" : "","IndustryIdArr" : "0","MainComIdArr" : "" },
	{ "KeyName" :"RegisterViewModel_ConfirmPassword" , "KeyType" : "ModalView_PropertyName", "zh_CN" : "确认密码","zh_HK" : "確認密碼","en_US" : "Confirmed Password","IndustryIdArr" : "","MainComIdArr" : "" },
	{ "KeyName" :"RegisterViewModel_EmailPhoneOrName" , "KeyType" : "ModalView_PropertyName", "zh_CN" : "Email或手机号","zh_HK" : "Email或手機號","en_US" : "Email,Phone,Name","IndustryIdArr" : "","MainComIdArr" : "" },
	{ "KeyName" :"RegisterViewModel_HasRegistedToLogin" , "KeyType" : "ModalView_PropertyName", "zh_CN" : "已经注册账号","zh_HK" : "已經注冊賬號","en_US" : "I Have Registed","IndustryIdArr" : "","MainComIdArr" : "" },
	{ "KeyName" :"RegisterViewModel_LoginNameTooltip" , "KeyType" : "ModalView_PropertyName", "zh_CN" : "使用Email注册","zh_HK" : "使用Email注冊","en_US" : "Email","IndustryIdArr" : "","MainComIdArr" : "" },
	{ "KeyName" :"RegisterViewModel_RegisterAsNewMember" , "KeyType" : "ModalView_PropertyName", "zh_CN" : "用户注册","zh_HK" : "用戶注冊","en_US" : "Register a New Id","IndustryIdArr" : "","MainComIdArr" : "" },
	{ "KeyName" :"RegisterViewModel_Title" , "KeyType" : "ModalView_PropertyName", "zh_CN" : "注册","zh_HK" : "注册","en_US" : "Register","IndustryIdArr" : "","MainComIdArr" : "" },
	{ "KeyName" :"RegisterViewModel_Welcome" , "KeyType" : "Modalview_PropertyName", "zh_CN" : "Welcome","zh_HK" : "Welcome","en_US" : "Welcome","IndustryIdArr" : "0","MainComIdArr" : "" },
	{ "KeyName" :"Shift_AppliedEndDate" , "KeyType" : "Modal_PropertyName", "zh_CN" : "排班应用结束日期","zh_HK" : "排班應用結束日期","en_US" : "Shift applied end date","IndustryIdArr" : "","MainComIdArr" : "" },
	{ "KeyName" :"Shift_AppliedStartDate" , "KeyType" : "Modal_PropertyName", "zh_CN" : "排班开始应用时间","zh_HK" : "排班開始應用時間","en_US" : "Applied Start Date","IndustryIdArr" : "","MainComIdArr" : "" },
	{ "KeyName" :"Shift_AppliedStartDateIsNotLogical_Validator" , "KeyType" : "ModalView_PropertyName", "zh_CN" : "应用开始日期与应用结束日期不合理","zh_HK" : "應用開始日期與應用結束日期不合理","en_US" : "Applied start date and Applied end date are not reasonable","IndustryIdArr" : "","MainComIdArr" : "" },
	{ "KeyName" :"Shift_AttendanceAllowance" , "KeyType" : "ModalView_PropertyName", "zh_CN" : "考勤允许多少分钟","zh_HK" : "考勤允許多少分鐘","en_US" : "Attendance Allowance","IndustryIdArr" : "","MainComIdArr" : "" },
	{ "KeyName" :"Shift_AttendanceAllowanceTips" , "KeyType" : "ModalView_PropertyName", "zh_CN" : "考勤允许值：指的是上下班迟到或早退，在指定范围时间内，不作早退或迟到，例如：9:01后上班就开始算作迟到，但加入允许值15分钟，9:16后才算是迟到，早退同理。","zh_HK" : "考勤允許值：指的是上下班遲到或早退，在指定范圍時間內，不作早退或遲到，例如：9:01后上班就開始算作遲到，但加入允許值15分鐘，9:16后才算是遲到，早退同理。","en_US" : "Attendance allowable value: refers to late or early leave of work, not early or late in the specified range of time, for example: 9:01 after work is counted as late, but the allowed value is 15 minutes, after 9:16 is considered Being late, leaving the same way.","IndustryIdArr" : "","MainComIdArr" : "" },
	{ "KeyName" :"Shift_AttendanceWorkBuffer" , "KeyType" : "ModalView_PropertyName", "zh_CN" : "有效考勤时间","zh_HK" : "有效考勤時間","en_US" : "Valid Attendance Time Buffer","IndustryIdArr" : "","MainComIdArr" : "" },
	{ "KeyName" :"Shift_AttendanceWorkBufferTips" , "KeyType" : "ModalView_PropertyName", "zh_CN" : "允许上班时间9:00之前，最早的有效记录时间，例如 7:00-9:00 的记录有效。早于7:00视为无效考勤时间","zh_HK" : "允許上班時間9:00之前，最早的有效記錄時間，例如 7:00-9:00 的記錄有效。早于7:00視為無效考勤時間","en_US" : "Allows the earliest valid recording time, such as 7:00-9:00, to be valid before 9:00. Invalid attendance time before 7:00","IndustryIdArr" : "","MainComIdArr" : "" },
	{ "KeyName" :"Shift_BreakTime" , "KeyType" : "ModalView_PropertyName", "zh_CN" : "休息时间","zh_HK" : "休息時間","en_US" : "Break Time","IndustryIdArr" : "","MainComIdArr" : "" },
	{ "KeyName" :"Shift_CompanyName" , "KeyType" : "Modal_PropertyName", "zh_CN" : "公司名称","zh_HK" : "公司名稱","en_US" : "Company Name","IndustryIdArr" : "","MainComIdArr" : "" },
	{ "KeyName" :"Shift_IsAutoCalcMissing" , "KeyType" : "Modal_PropertyName", "zh_CN" : "漏打卡，允许自动计算","zh_HK" : "漏打卡，允許自動計算","en_US" : "Is Auto Calc Missing","IndustryIdArr" : "","MainComIdArr" : "" },
	{ "KeyName" :"Shift_LunchTime_Lbl" , "KeyType" : "ModalView_PropertyName", "zh_CN" : "午餐时间","zh_HK" : "午餐時間","en_US" : "Lunch Time","IndustryIdArr" : "","MainComIdArr" : "" },
	{ "KeyName" :"Shift_MainComId" , "KeyType" : "Modal_PropertyName", "zh_CN" : "Main Com Id","zh_HK" : "Main Com Id","en_US" : "Main Com Id","IndustryIdArr" : "","MainComIdArr" : "" },
	{ "KeyName" :"Shift_Return_Update_Success" , "KeyType" : "ModalView_PropertyName", "zh_CN" : "返回更新成功","zh_HK" : "返回更新成功","en_US" : "Update Success","IndustryIdArr" : "","MainComIdArr" : "" },
	{ "KeyName" :"Shift_ReturnSuccess" , "KeyType" : "ModalView_PropertyName", "zh_CN" : "返回成功","zh_HK" : "返回成功","en_US" : "Success","IndustryIdArr" : "","MainComIdArr" : "" },
	{ "KeyName" :"Shift_RuleDescription" , "KeyType" : "Modal_PropertyName", "zh_CN" : "排班规则说明","zh_HK" : "排班規則說明","en_US" : "Rule Descriptions","IndustryIdArr" : "","MainComIdArr" : "" },
	{ "KeyName" :"Shift_Shift_SpecialWeekDaysTips" , "KeyType" : "ModalView_PropertyName", "zh_CN" : "按星期特定上下班时间，例如星期六：9:00-13:00，星期天属于公众假期的情况下，已被假日设置排除，无需勾选。","zh_HK" : "按星期定義上下班時間，例如星期六：9:00-13:00，星期天屬於公眾假期的情況下，已被假日設置排除，無需勾選。","en_US" : "Special weekday work time definition，e.g. SAT : 9:00-13:00。SunDay is belong to StatutoryHoliday,so it needn't select.","IndustryIdArr" : "","MainComIdArr" : "" },
	{ "KeyName" :"Shift_ShiftAbbrId" , "KeyType" : "Modal_PropertyName", "zh_CN" : "缩写ID","zh_HK" : "縮寫ID","en_US" : "The Abbr ID.","IndustryIdArr" : "","MainComIdArr" : "" },
	{ "KeyName" :"Shift_ShiftAbbrId_Required" , "KeyType" : "ModalView_PropertyName", "zh_CN" : "缩写ID是必须的，用於提升报表的可读性。","zh_HK" : "縮寫ID是必須的，用於提升報表的可讀性。","en_US" : "The abbreviation ID is required to improve the readability of the report.","IndustryIdArr" : "","MainComIdArr" : "" },
	{ "KeyName" :"Shift_ShiftAppliedMode" , "KeyType" : "Modal_PropertyName", "zh_CN" : "排班应用模式","zh_HK" : "排班應用模式","en_US" : "Shift Applied Mode","IndustryIdArr" : "","MainComIdArr" : "" },
	{ "KeyName" :"Shift_ShiftBusinessMode" , "KeyType" : "Modal_PropertyName", "zh_CN" : "排班业务模式","zh_HK" : "排班業務模式","en_US" : "Shift Business Mode","IndustryIdArr" : "","MainComIdArr" : "" },
	{ "KeyName" :"Shift_ShiftId" , "KeyType" : "Modal_PropertyName", "zh_CN" : "ID","zh_HK" : "ID","en_US" : "Shift Id","IndustryIdArr" : "","MainComIdArr" : "" },
	{ "KeyName" :"Shift_ShiftName" , "KeyType" : "Modal_PropertyName", "zh_CN" : "排班设置名称","zh_HK" : "排班設置名稱","en_US" : "Shift Name","IndustryIdArr" : "","MainComIdArr" : "" },
	{ "KeyName" :"Shift_ShiftName_Required" , "KeyType" : "ModalView_PropertyName", "zh_CN" : "请输入排班名称","zh_HK" : "請輸入排班名稱","en_US" : "Please input valid shift name","IndustryIdArr" : "","MainComIdArr" : "" },
	{ "KeyName" :"Shift_ShiftSettingBreak" , "KeyType" : "ModalView_PropertyName", "zh_CN" : "设置小息时段","zh_HK" : "設置小息時段","en_US" : "Set Breaktime","IndustryIdArr" : "","MainComIdArr" : "" },
	{ "KeyName" :"Shift_ShiftSettingLunch" , "KeyType" : "ModalView_PropertyName", "zh_CN" : "設置午餐時段","zh_HK" : "設置午餐時段","en_US" : "Set LunchTime","IndustryIdArr" : "","MainComIdArr" : "" },
	{ "KeyName" :"Shift_ShiftSettingNight" , "KeyType" : "Modal_PropertyName", "zh_CN" : "Turn to 夜更设置","zh_HK" : "Turn to 夜更设置","en_US" : "Turn to NightShift","IndustryIdArr" : "","MainComIdArr" : "" },
	{ "KeyName" :"Shift_ShiftSettingOverTime" , "KeyType" : "Modal_PropertyName", "zh_CN" : "Turn to 加班OT Shift","zh_HK" : "Turn to 加班OT Shift","en_US" : "Turn to OverTimeShift","IndustryIdArr" : "","MainComIdArr" : "" },
	{ "KeyName" :"Shift_ShiftSettingWeekDay" , "KeyType" : "ModalView_PropertyName", "zh_CN" : "Turn to 按星期设更","zh_HK" : "Turn to 按星期设更","en_US" : "Turn to WeekdayShift","IndustryIdArr" : "","MainComIdArr" : "" },
	{ "KeyName" :"Shift_SimpleCalc" , "KeyType" : "ModalView_PropertyName", "zh_CN" : "简单计算（Day）","zh_HK" : "簡單計算（Day）","en_US" : "Simple Calc（Day Shift）","IndustryIdArr" : "","MainComIdArr" : "" },
	{ "KeyName" :"Shift_SpecialWeekDays" , "KeyType" : "Modal_PropertyName", "zh_CN" : "每星期特别日","zh_HK" : "每星期特別日","en_US" : "Special Week Days","IndustryIdArr" : "","MainComIdArr" : "" },
	{ "KeyName" :"Shift_SpecialWeekDays_WorkTime" , "KeyType" : "Modal_PropertyName", "zh_CN" : "指定星期的工作时间","zh_HK" : "指定星期的工作時間","en_US" : "WorkTime Of Special WeekDay","IndustryIdArr" : "","MainComIdArr" : "" },
	{ "KeyName" :"Shift_WorkEnd" , "KeyType" : "Modal_PropertyName", "zh_CN" : "下班时间","zh_HK" : "下班時間","en_US" : "Work End","IndustryIdArr" : "","MainComIdArr" : "" },
	{ "KeyName" :"Shift_WorkEnd_Required" , "KeyType" : "ModalView_PropertyName", "zh_CN" : "请输入工作结束时间","zh_HK" : "請輸入工作結束時間","en_US" : "Please input valid work end ,required.","IndustryIdArr" : "","MainComIdArr" : "" },
	{ "KeyName" :"Shift_WorkEndAllowance" , "KeyType" : "Modal_PropertyName", "zh_CN" : "工作结束的宽限时间","zh_HK" : "工作结束的寬限時間","en_US" : "Work End Allowance","IndustryIdArr" : "","MainComIdArr" : "" },
	{ "KeyName" :"Shift_WorkEndAllowance_Required" , "KeyType" : "ModalView_PropertyName", "zh_CN" : "请输入工作结束的宽限时间","zh_HK" : "請輸入工作結束的寬限時間","en_US" : "Please input work end allowance.","IndustryIdArr" : "","MainComIdArr" : "" },
	{ "KeyName" :"Shift_WorkEndBuffer" , "KeyType" : "Modal_PropertyName", "zh_CN" : "下班考勤允许时间范围","zh_HK" : "下班考勤允許時間范圍","en_US" : "Work End Buffer","IndustryIdArr" : "","MainComIdArr" : "" },
	{ "KeyName" :"Shift_WorkEndBuffer_Required" , "KeyType" : "ModalView_PropertyName", "zh_CN" : "请输入有效考勤结束时间","zh_HK" : "請輸入有效考勤結束時間","en_US" : "Please input work start buffer.","IndustryIdArr" : "","MainComIdArr" : "" },
	{ "KeyName" :"Shift_WorkStart" , "KeyType" : "Modal_PropertyName", "zh_CN" : "上班时间","zh_HK" : "上班時間","en_US" : "Work Start","IndustryIdArr" : "","MainComIdArr" : "" },
	{ "KeyName" :"Shift_WorkStart_Required" , "KeyType" : "ModalView_PropertyName", "zh_CN" : "请输入工作开始时间","zh_HK" : "請輸入工作開始時間","en_US" : "Please input valid work start ,required.","IndustryIdArr" : "","MainComIdArr" : "" },
	{ "KeyName" :"Shift_WorkStartAllowance" , "KeyType" : "Modal_PropertyName", "zh_CN" : "工作开始的宽限时间","zh_HK" : "工作开始的宽限时间","en_US" : "Work Start Allowance","IndustryIdArr" : "","MainComIdArr" : "" },
	{ "KeyName" :"Shift_WorkStartAllowance_Required" , "KeyType" : "ModalView_PropertyName", "zh_CN" : "请输入工作开始的宽限时间","zh_HK" : "請輸入工作開始的寬限時間","en_US" : "Please input work start allowance.","IndustryIdArr" : "","MainComIdArr" : "" },
	{ "KeyName" :"Shift_WorkStartBuffer" , "KeyType" : "Modal_PropertyName", "zh_CN" : "上班考勤允许时间范围","zh_HK" : "工作開始的寬限時間","en_US" : "Work Start Buffer","IndustryIdArr" : "","MainComIdArr" : "" },
	{ "KeyName" :"Shift_WorkStartBuffer_Required" , "KeyType" : "ModalView_PropertyName", "zh_CN" : "请输入有效开始考勤时间","zh_HK" : "請輸入有效開始考勤時間","en_US" : "Please input work start buffer.","IndustryIdArr" : "","MainComIdArr" : "" },
	{ "KeyName" :"Shift_WorkTimeSpan" , "KeyType" : "Modal_PropertyName", "zh_CN" : "工作时间设置","zh_HK" : "工作時間設置","en_US" : "Work Time","IndustryIdArr" : "","MainComIdArr" : "" },
	{ "KeyName" :"ShiftAppliedMode_GLOBAL" , "KeyType" : "Modal_PropertyName", "zh_CN" : "全局模式","zh_HK" : "全局模式","en_US" : "GLOBAL","IndustryIdArr" : "","MainComIdArr" : "" },
	{ "KeyName" :"ShiftAppliedMode_PARTIAL" , "KeyType" : "Modal_PropertyName", "zh_CN" : "自定义模式","zh_HK" : "自定义模式","en_US" : "PARTIAL(DEF)","IndustryIdArr" : "","MainComIdArr" : "" },
	{ "KeyName" :"ShiftAssignedMode_MANUAL_ASSIGNED" , "KeyType" : "Modal_PropertyName", "zh_CN" : "手动指派","zh_HK" : "手動指派","en_US" : "MANUAL ASSIGNED","IndustryIdArr" : "","MainComIdArr" : "" },
	{ "KeyName" :"ShiftAssignedMode_SYSTEM_ASSIGNED" , "KeyType" : "Modal_PropertyName", "zh_CN" : "系统指派","zh_HK" : "系統指派","en_US" : "SYSTEM ASSIGNED","IndustryIdArr" : "","MainComIdArr" : "" },
	{ "KeyName" :"ShiftBusinessMode_CROSSDAYSSHIFT" , "KeyType" : "Modal_PropertyName", "zh_CN" : "跨日计算模式","zh_HK" : "跨日計算模式","en_US" : "CROSS DAY STHIFT","IndustryIdArr" : "","MainComIdArr" : "" },
	{ "KeyName" :"ShiftBusinessMode_DAYSHIFT" , "KeyType" : "Modal_PropertyName", "zh_CN" : "日更计算模式","zh_HK" : "日更計算模式","en_US" : "DAY THIFT","IndustryIdArr" : "","MainComIdArr" : "" },
	{ "KeyName" :"ShiftBusinessMode_GENERAL" , "KeyType" : "Modal_PropertyName", "zh_CN" : "通用更期计算模式","zh_HK" : "通用更期計算模式","en_US" : "GENERAL THIFT","IndustryIdArr" : "","MainComIdArr" : "" },
	{ "KeyName" :"ShiftBusinessMode_NIGHTSHIFT" , "KeyType" : "Modal_PropertyName", "zh_CN" : "夜更计算模式","zh_HK" : "夜更計算模式","en_US" : "NIGHT THIFT","IndustryIdArr" : "","MainComIdArr" : "" },
	{ "KeyName" :"ShiftBusinessMode_OVERNIGHTSHIFT" , "KeyType" : "Modal_PropertyName", "zh_CN" : "通宵计算模式","zh_HK" : "通宵計算模式","en_US" : "OVER NIGHT THIFT","IndustryIdArr" : "","MainComIdArr" : "" },
	{ "KeyName" :"ShiftBusinessMode_THREESHIFT" , "KeyType" : "Modal_PropertyName", "zh_CN" : "三班制计算模式","zh_HK" : "三班制計算模式","en_US" : "THREETHIFT","IndustryIdArr" : "","MainComIdArr" : "" },
	{ "KeyName" :"ShiftSetting_Title" , "KeyType" : "ModalView_PropertyName", "zh_CN" : "排班表","zh_HK" : "排班表","en_US" : "Shift Setting","IndustryIdArr" : "","MainComIdArr" : "" },
	{ "KeyName" :"Trade_CreatedDate" , "KeyType" : "Modal_PropertyName", "zh_CN" : "CreatedDate","zh_HK" : "CreatedDate","en_US" : "CreatedDate","IndustryIdArr" : "0","MainComIdArr" : "" },
	{ "KeyName" :"Trade_EnPositionTitle" , "KeyType" : "Modal_PropertyName", "zh_CN" : "Position Eng Title","zh_HK" : "Position Eng Title","en_US" : "Eng PositionTitle","IndustryIdArr" : "0","MainComIdArr" : "" },
	{ "KeyName" :"User_UserRolesAssignedUpdate_UpdateRolesFail" , "KeyType" : "ModalView_PropertyName", "zh_CN" : "更新角色失败 !","zh_HK" : "更新角色失敗 !","en_US" : "UpdateRolesFail ！","IndustryIdArr" : "0","MainComIdArr" : "" },
	{ "KeyName" :"User_UserRolesAssignedUpdate_UpdateRolesSuccess" , "KeyType" : "ModalView_PropertyName", "zh_CN" : "更新角色成功!","zh_HK" : "更新角色成功!","en_US" : "Update Roles Success！","IndustryIdArr" : "0","MainComIdArr" : "" },
	{ "KeyName" :"UserList_Associate" , "KeyType" : "ModalView_PropertyName", "zh_CN" : "关 联","zh_HK" : "關 聯","en_US" : "Associate","IndustryIdArr" : "0","MainComIdArr" : "" },
	{ "KeyName" :"UserList_CancelAssociate" , "KeyType" : "ModalView_PropertyName", "zh_CN" : "取消关联","zh_HK" : "取消關聯","en_US" : "Cancel Associate","IndustryIdArr" : "0","MainComIdArr" : "" },
	{ "KeyName" :"UserList_RolesAuthorize" , "KeyType" : "ModalView_PropertyName", "zh_CN" : "角色授权","zh_HK" : "角色授權","en_US" : "Roles Authorize","IndustryIdArr" : "0","MainComIdArr" : "" },
	{ "KeyName" :"UserList_Title" , "KeyType" : "ModalView_PropertyName", "zh_CN" : "系统用户列表","zh_HK" : "系統用戶列表","en_US" : "System User List","IndustryIdArr" : "0","MainComIdArr" : "" },
	{ "KeyName" :"UserRegister_AddNew" , "KeyType" : "ModalView_PropertyName", "zh_CN" : "新 增","zh_HK" : "新 增","en_US" : "Add New","IndustryIdArr" : "0","MainComIdArr" : "" },
	{ "KeyName" :"UserRegister_MayBeInputIllegalData" , "KeyType" : "ModalView_PropertyName", "zh_CN" : "可能输入非法数据！","zh_HK" : "可能輸入非法數據！","en_US" : "MayBe Input Illegal Data ！","IndustryIdArr" : "0","MainComIdArr" : "" },
	{ "KeyName" :"UserRegister_NeedToAddEmployee" , "KeyType" : "ControllerName_ActionMethod_JsMethod_JsVar", "zh_CN" : "现在添加雇员资料吗？","zh_HK" : "現在添加雇員資料嗎？","en_US" : "Need To Add Employee？","IndustryIdArr" : "0","MainComIdArr" : "" },
	{ "KeyName" :"UserRegister_RefuseUserRegisterTips" , "KeyType" : "ModalView_PropertyName", "zh_CN" : "No，现在不需要添加雇员资料","zh_HK" : "No，現在不需要添加雇員資料","en_US" : "No，Now not yet.","IndustryIdArr" : "0","MainComIdArr" : "" },
	{ "KeyName" :"UserRegister_RegistedFailure" , "KeyType" : "ModalView_PropertyName", "zh_CN" : "注册失败 ！","zh_HK" : "注冊失敗 ！","en_US" : "Registed Failure ！","IndustryIdArr" : "0","MainComIdArr" : "" },
	{ "KeyName" :"UserRegister_RegistedSuccess" , "KeyType" : "ModalView_PropertyName", "zh_CN" : "注册成功 ！","zh_HK" : "注冊成功 ！","en_US" : "Registed Success ！","IndustryIdArr" : "0","MainComIdArr" : "" },
	{ "KeyName" :"UserRegister_Title" , "KeyType" : "ModalView_PropertyName", "zh_CN" : "系统用户注册","zh_HK" : "系統用戶注冊","en_US" : "System User Restistration","IndustryIdArr" : "0","MainComIdArr" : "" },
	{ "KeyName" :"UserRolesAssignList_RolesAssign" , "KeyType" : "ModalView_PropertyName", "zh_CN" : "角色授权","zh_HK" : "角色授權","en_US" : "Roles Assignment","IndustryIdArr" : "0","MainComIdArr" : "" },
	{ "KeyName" :"UserRolesAssignList_Title" , "KeyType" : "ModalView_PropertyName", "zh_CN" : "用户角色授权","zh_HK" : "用戶角色授權","en_US" : "User Roles Assignment","IndustryIdArr" : "0","MainComIdArr" : "" },
	{ "KeyName" :"Views_GeneralUI_Register" , "KeyType" : "ModalView_PropertyName", "zh_CN" : "注 册","zh_HK" : "注 冊","en_US" : "Regist","IndustryIdArr" : "","MainComIdArr" : "" },
	{ "KeyName" :"WeekDayType_FRIDAY" , "KeyType" : "Modal_PropertyName", "zh_CN" : "FRIDAY","zh_HK" : "FRIDAY","en_US" : "FRIDAY","IndustryIdArr" : "","MainComIdArr" : "" },
	{ "KeyName" :"WeekDayType_MONDAY" , "KeyType" : "Modal_PropertyName", "zh_CN" : "MONDAY","zh_HK" : "MONDAY","en_US" : "MONDAY","IndustryIdArr" : "","MainComIdArr" : "" },
	{ "KeyName" :"WeekDayType_SATURDAY" , "KeyType" : "Modal_PropertyName", "zh_CN" : "SATURDAY","zh_HK" : "SATURDAY","en_US" : "SATURDAY","IndustryIdArr" : "","MainComIdArr" : "" },
	{ "KeyName" :"WeekDayType_SUNDAY" , "KeyType" : "Modal_PropertyName", "zh_CN" : "SUNDAY","zh_HK" : "SUNDAY","en_US" : "SUNDAY","IndustryIdArr" : "","MainComIdArr" : "" },
	{ "KeyName" :"WeekDayType_THURSDAY" , "KeyType" : "Modal_PropertyName", "zh_CN" : "THURSDAY","zh_HK" : "THURSDAY","en_US" : "THURDAY","IndustryIdArr" : "","MainComIdArr" : "" },
	{ "KeyName" :"WeekDayType_TUEDAY" , "KeyType" : "Modal_PropertyName", "zh_CN" : "TUEDAY","zh_HK" : "TUEDAY","en_US" : "TUEDAY","IndustryIdArr" : "","MainComIdArr" : "" },
	{ "KeyName" :"WeekDayType_WEDNESDAY" , "KeyType" : "Modal_PropertyName", "zh_CN" : "WEDNESDAY","zh_HK" : "WEDNESDAY","en_US" : "WEDNESDAY","IndustryIdArr" : "","MainComIdArr" : "" }]
